#ifndef _SUBSPACETEXTURE_H_
#define _SUBSPACETEXTURE_H_

#include <string>
using std::string;

#include "TextureAnimated.h"

enum TextureType
{
	TEX_BG01,
	TEX_BG02,
	TEX_BG03,
	TEX_BG04,
	TEX_BG05,
	TEX_BG06,
	TEX_BG07,
	TEX_BG08,
	TEX_BG09,
	TEX_BG10,
	TEX_BG11,
	TEX_BG12,
	TEX_BG13,
	TEX_BG14,
	TEX_BombFlash,
	TEX_Bombs,
	TEX_Bullets,
	TEX_Damage,
	TEX_Disp,
	TEX_DropFlag,
	TEX_EmpBurst,
	TEX_EnergyFont,
	TEX_Exhaust,
	TEX_Explode0,
	TEX_Explode1,
	TEX_Explode2,
	TEX_Flag,
	TEX_Goal,
	TEX_Gradient,
	TEX_HealthBar,
	TEX_HugeFont,
	TEX_HugeFontF,
	TEX_IconDoor,
	TEX_Icons,
	TEX_JunkJavelin,
	TEX_JunkLeviathan,
	TEX_JunkNightwasp,
	TEX_JunkShark,
	TEX_JunkSpider,
	TEX_JunkTerrier,
	TEX_JunkWarbird,
	TEX_JunkWeasel,
	TEX_JavelinRoll,
	TEX_King,
	TEX_KingEx,
	TEX_LargeFont,
	TEX_LargeFontF,
	TEX_Led,
	TEX_LeviathanRoll,
	TEX_MenuText,
	TEX_Mines,
	TEX_NightwaspRoll,
	TEX_Over1,
	TEX_Over2,
	TEX_Over3,
	TEX_Over4,
	TEX_Over5,
	TEX_Powerball,
	TEX_Prizes,
	TEX_RadarH,
	TEX_RadarV,
	TEX_Repel,
	TEX_Rocket,
	TEX_Shield,
	TEX_Ships,
	TEX_Shrapnel,
	TEX_SharkRoll,
	TEX_ShortFont,
	TEX_Spark,
	TEX_SpecFont,
	TEX_Spectate,
	TEX_SpiderRoll,
	TEX_SSShield,
	TEX_Star01,
	TEX_Star02,
	TEX_Star03,
	TEX_Star04,
	TEX_Star05,
	TEX_Star06,
	TEX_Star07,
	TEX_Super,
	TEX_TallFont,
	TEX_TallFontF,
	TEX_TerrierRoll,
	TEX_Tiles,
	TEX_Trail,
	TEX_Turret,
	TEX_Turret2,
	TEX_Wall,
	TEX_Warp,
	TEX_WarpPoint,
	TEX_WarbirdRoll,
	TEX_WeaselRoll,

	TEX_NumTextures
};

extern TextureAnimated subspaceTextures[TEX_NumTextures];

void loadSubspaceTextures(const string& path);

#endif